# Dependabot config
# https://dependabot.com/docs/config-file/
# Checks and updates dependencies in
# `requirements.txt`
# and the Dockerfile at the repository root

version: 1
update_configs:
  - package_manager: "python"
    directory: "/"
    update_schedule: "weekly"
    allowed_updates:
      - match:
          dependency_type: "production"
          update_type: "all"

  - package_manager: "docker"
    directory: "/"
    update_schedule: "weekly"
